# Generated by Django 3.2.15 on 2022-12-11 10:49

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='+7 999 999 99 99', max_length=20, unique=True, validators=[users.validators.user_phonenumber_validator], verbose_name='Номер телефона пользователя'),
        ),
    ]
