# Generated by Django 3.2.15 on 2022-11-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vk_posts',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID поста')),
                ('date', models.DateField(verbose_name='Дата поста')),
                ('text_post', models.TextField(max_length=4096, verbose_name='Текст поста')),
                ('photo', models.TextField(max_length=4096, verbose_name='Фото поста')),
            ],
            options={
                'verbose_name': 'Модель поста из Vk',
                'verbose_name_plural': 'Модели постов из Vk',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='VkPostModel',
        ),
    ]
