# Generated by Django 3.2.15 on 2022-12-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostToVk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст поста')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Модель для постинга в Vk',
                'verbose_name_plural': 'Модели для постинга в Vk',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VkPosts',
            fields=[
                ('id', models.CharField(default='бд дополнит', max_length=15, primary_key=True, serialize=False, verbose_name='ID поста')),
                ('date', models.DateField(verbose_name='Дата поста')),
                ('text_post', models.TextField(max_length=4096, verbose_name='Текст поста')),
                ('photo', models.TextField(max_length=4096, verbose_name='Фото поста')),
            ],
            options={
                'verbose_name': 'Модель поста из Vk',
                'verbose_name_plural': 'Модели постов из Vk',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='Vk_posts',
        ),
    ]
