# Generated by Django 3.2.15 on 2022-12-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_posts', '0002_auto_20221211_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VkPosts',
            new_name='Vk_posts',
        ),
    ]
